### ISSUE TITLE
Incorrect URL To TextVQA Website Code Source

### ISSUE THREAD

**Issue by Totoola-Kehinde** [facebookresearch/TextVQA#7]
Hi there,

I think this is an error:
The link for the website code source(TextVQA Source) is incorrect!
This link is live on the website[code](https://github.com/facebookresearch/pythia) which redirects to MMF code source [code](https://github.com/facebookresearch/mmf)

The actual link for the TextVQA source is [code](https://github.com/facebookresearch/TextVQA/)
![TextVQA](https://user-images.githubusercontent.com/40864358/89467352-5377f900-d76d-11ea-8bda-54125f5681c5.PNG)

**Comment by Totoola-Kehinde** [comment]
I will be making a PR of the updated link now!

**Comment by apsdehal** [comment]
Hi @Totoola-Kehinde,
The link to MMF is expected as that is the starter code for Textvqa. We should redirect to correct project page of TextVQA in MMF though. Can you update your PR to reflect that? Thanks

**Comment by Totoola-Kehinde** [comment]
Hi @apsdehal I just updated the code to reflect the mmf code source as that starter code for Textvqa.

Thank you
